// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKg_sVegc-ZZF_d-rp8mUjt11QS08FAb4',
    appId: '1:31008879665:ios:30b81197ddba65f0ec1110',
    messagingSenderId: '31008879665',
    projectId: 'lost-and-found-system-d6b2d',
    storageBucket: 'lost-and-found-system-d6b2d.firebasestorage.app',
    iosBundleId: 'com.example.lostFoundApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKg_sVegc-ZZF_d-rp8mUjt11QS08FAb4',
    appId: '1:31008879665:ios:30b81197ddba65f0ec1110',
    messagingSenderId: '31008879665',
    projectId: 'lost-and-found-system-d6b2d',
    storageBucket: 'lost-and-found-system-d6b2d.firebasestorage.app',
    iosBundleId: 'com.example.lostFoundApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnY4lfEVznAWDvPrY6PNvNNfAKbfZ-2og',
    appId: '1:31008879665:web:c57f1dbc06911622ec1110',
    messagingSenderId: '31008879665',
    projectId: 'lost-and-found-system-d6b2d',
    authDomain: 'lost-and-found-system-d6b2d.firebaseapp.com',
    storageBucket: 'lost-and-found-system-d6b2d.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnY4lfEVznAWDvPrY6PNvNNfAKbfZ-2og',
    appId: '1:31008879665:web:c57f1dbc06911622ec1110',
    messagingSenderId: '31008879665',
    projectId: 'lost-and-found-system-d6b2d',
    authDomain: 'lost-and-found-system-d6b2d.firebaseapp.com',
    storageBucket: 'lost-and-found-system-d6b2d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcl0iTGtE4MprbXT7yytncEOBw02LArC4',
    appId: '1:31008879665:android:4086dc18b205d24fec1110',
    messagingSenderId: '31008879665',
    projectId: 'lost-and-found-system-d6b2d',
    storageBucket: 'lost-and-found-system-d6b2d.firebasestorage.app',
  );

}